event/controllers/HandlerController.php
<?php
namespace event\controllers;

use Yii;
use yii\web\Controller;
use yii\db\Query;
use yii\helpers\Url;
use event\models\Event;
use event\models\users\User;
use event\models\users\Users;
use event\models\users\UsersConfirm;
use event\models\users\UsersSession;
use event\models\users\UsersHistory;
use event\models\users\UsersRecovery;
use event\models\users\UsersAccess;
use event\models\db\Events;
use event\models\db\Favorites;
use event\models\db\Likes;
use event\models\db\Schedule;
use event\models\db\QuestionsSettings;
use event\models\db\LotteryUsers;
use event\models\helpers\FileHelper;
use common\models\helpers\FormatHelper;
use common\models\sms;
use event\models\is1c2020;

class HandlerController extends Controller {
    private $user;

    public function beforeAction($action) {
        $this->user = new User();
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action);
    }

    public function actionHandler() {
        $this->layout = false;
        $method = Yii::$app->request->get('method');
        $result = false;

        if ($method == 'sms') {
            if (!Yii::$app->request->cookies->has('trace')) return $this->redirect(['auth/confirm', 'response' => 'fail']);
            $trace = htmlspecialchars(Yii::$app->request->cookies->get('trace')->value);

            $date = (new \DateTime('-50 seconds'))->format('Y-m-d H:i:s');

            $query = UsersConfirm::find()
                ->select('user_id')
                ->where(['trace' => $trace])
                ->andWhere(['<', 'date', $date])
                ->one();

            if (!$query) return $this->redirect(['auth/confirm', 'response' => 'fail']);

            $query = Users::find()
                ->select(['id', 'login'])
                ->where(['id' => $query->user_id])
                ->one();

            if (!$query) return $this->redirect(['auth/confirm', 'response' => 'fail']);
            
            $code = $this->user->generateCode(10000, 99999);

            $sms_phone = '7' . $query->login;
            $sms_message = 'ИнфоСофт код подтверждения: ' . $code;
            $sms = (new SMS())->sendSms($sms_phone, $sms_message);

            if ($sms) {
                (new Query())->createCommand()
                    ->update('users_confirm', ['code' => $code, 'date' => date('Y-m-d H:i:s')], ['user_id' => $query->id, 'trace' => $trace])
                    ->execute();

                return $this->redirect(['auth/confirm', 'response' => 'success']);
            } else {
                return $this->redirect(['auth/confirm', 'response' => 'fail']);
            }

            $result = true;
        } elseif ($method == 'add-users') {
            $json = json_decode($_POST['vars']);
            $event_id = $json->EventNum;
            $users = $json->Users;

            $phones = [];
            foreach ($users as $user) {
                $phones[] = FormatHelper::phone($user->Num);
            }

            $exist_users = Users::find()
                ->select(['id', 'login'])
                ->where(['login' => $phones])
                ->all();

            // Зарегистрированные пользователи
            $exist_ids = [];
            $exist_phones = [];
            foreach ($exist_users as $user) {
                $exist_ids[] = $user->id;
                $exist_phones[] = $user->login;
            }

            $exist_access = UsersAccess::find()
                ->select('user_id')
                ->where(['event_id' => $event_id, 'user_id' => $exist_ids])
                ->all();

            // Пользователи уже имеющие доступ к конференции
            $exist_access_ids = [];
            foreach ($exist_access as $user) {
                $exist_access_ids[] = $user->user_id;
            }

            $users_to_insert = [];
            foreach ($users as $user) {
                if (!in_array($user->Num, $exist_phones) && $user->User != '' && $user->Num != '') {
                    $users_to_insert[] = [
                        'login' => FormatHelper::phone($user->Num),
                        'name' => htmlspecialchars($user->User),
                        'email' => ($user->Email != '' && $this->user->emailValidate($user->Email)) ? htmlspecialchars($user->Email) : NULL,
                        'role' => 1
                    ];
                }
            }

            (new Query())->createCommand()
                ->batchInsert('users', ['login', 'name', 'email', 'role'], $users_to_insert)
                ->execute();

            // Зарегистрированные пользователи, без доступа к конференции
            $users_to_access = [];
            foreach ($exist_ids as $user) {
                if (!in_array($user, $exist_access_ids)) {
                    $users_to_access[$user] = [
                        'user_id' => $user,
                        'event_id' => $event_id,
                        'active' => 1
                    ];
                }
            }

            $inserted_users = Users::find()
                ->select('id')
                ->where(['login' => $phones])
                ->all();

            foreach ($inserted_users as $user) {
                if (!in_array($user->id, $exist_access_ids)) {
                    $users_to_access[$user->id] = [
                        'user_id' => $user->id,
                        'event_id' => $event_id,
                        'active' => 1
                    ];
                }
            }

            (new Query())->createCommand()
                ->batchInsert('users_access', ['user_id', 'event_id', 'active'], $users_to_access)
                ->execute();

            $result = 'true';
        } elseif ($method == 'is1c2020') {
            $name = htmlspecialchars(trim($_GET['name']));
            $surname = htmlspecialchars(trim($_GET['surname']));
            $company = htmlspecialchars(trim($_GET['company']));
            $position = htmlspecialchars(trim($_GET['position']));
            $city = htmlspecialchars(trim($_GET['city']));
            $section = htmlspecialchars(trim($_GET['section']));
            $email = htmlspecialchars(trim($_GET['email']));
            $phone = htmlspecialchars(trim($_GET['phone']));
            $ip = htmlspecialchars(trim($_GET['ip']));

            if ($name && $surname && $company && $position && $city && $email && $phone) {
                $exist = is1c2020::find()
                    ->select('id')
                    ->where(['email' => $email])
                    ->orWhere(['phone' => $phone])
                    ->one();

                if (!$exist) {
                    $query = (new Query())->createCommand()
                        ->insert('is1c2020', [
                            'name' => $name,
                            'surname' => $surname,
                            'company' => $company,
                            'position' => $position,
                            'city' => $city,
                            'section' =>$section,
                            'email' => $email,
                            'phone' => $phone,
                            'ip' => $ip
                        ])
                        ->execute();

                    if ($query) {
                        $text = 'Здравствуйте, ' . $name . '!<br><br>Вы успешно зарегистрированы как участник конференции IS1C2020.';
                        Yii::$app->mailer->compose('layouts/template', ['content' => $text, 'links' => false])
                            ->setFrom('my@is1c.ru')
                            ->setTo($email)
                            ->setSubject('Регистрация на IS1C2020')
                            ->send();

                        $result = 'true';
                    } else {
                        $result = 'false';
                    }
                } else {
                    $result = 'exist';
                }
            } else {
                $result = 'false';
            }
        }

        if ($result) {
            return $this->render('handler', [
                'result' => $result
            ]);
        }

        throw new \yii\web\NotFoundHttpException();
    }

    public function actionEvent() {
        $this->layout = false;
        $method = Yii::$app->request->get('method');
        $result = false;

        // Добавить/удалить доклад из избранного
        if ($method == 'schedule-favorite') {
            $event = Yii::$app->request->get('event');
            $schedule = Yii::$app->request->get('schedule');

            if ($event && $schedule) {
                $data = [
                    'user_id' => $this->user->getID(),
                    'event_id' => (int) $event,
                    'schedule_id' => (int) $schedule
                ];

                $favorite = Favorites::find()
                    ->select('id')
                    ->where($data)
                    ->one();

                if ($favorite) {
                    Favorites::deleteAll($data);
                    $result = 'delete';
                } else {
                    (new Query())->createCommand()
                        ->insert('favorites', $data)
                        ->execute();
                    $result = 'add';
                }
            }
        // Поставить/Убрать лайк вопросу
        } elseif ($method == 'question-like') {
            $schedule = Yii::$app->request->get('schedule');
            $question = Yii::$app->request->get('question');

            if ($schedule && $question) {
                $data = [
                    'user_id' => $this->user->getID(),
                    'schedule_id' => (int) $schedule,
                    'question_id' => (int) $question
                ];

                $like = Likes::find()
                    ->select('id')
                    ->where($data)
                    ->one();

                if ($like) {
                    Likes::deleteAll($data);

event/views/site/error.php
<?php
use yii\helpers\Url;
if ($exception->statusCode == 404) {
    $this->title = 'Страница не найдена';
    $error = 'Страница не найдена';
} else {
    $this->title = 'Ошибка';
    $error = 'Произошла ошибка';
}
?>
<div class="error-page">
    <div class="error-container">
        <div class="error-code"><?=$exception->statusCode; ?></div>
        <div class="error-desc"><?=$error; ?></div>
        <div class="error-action"><a href="<?=Url::to(['site/index']); ?>">Вернуться на главную</a></div>
    </div>
</div>

event/views/site/favorites.php
<?php
$this->title = 'Избранное - ' . $event['title'];
use common\widgets\Alert;
use yii\helpers\Url;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                    <h1 class="event-title mb-2">Избранное</h1>
                    <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                    <?php foreach ($schedule as $day_key => $day_value) : ?>
                        <?php if ($days) : ?>
                            <div class="pb-4">
                                <h3 class="mb-1"><i class="far fa-calendar-alt text-primary"></i> <?=$days[$day_key]; ?></h3>
                        <?php endif; ?>
                        <?php foreach ($day_value as $section_key => $section_value) : ?>
                            <div class="h4 mb-2"><i class="fas fa-bullhorn text-primary"></i> <?=$sections[$section_key]; ?></div>
                            <?php foreach ($section_value as $value) : ?>
                                <?=$this->render('@event/views/_item/schedule-' . $value['type'], ['result' => $value, 'tab' => $day_key]); ?>
                            <?php endforeach; // $section_value as $value ?>
                        <?php endforeach; // $day_value['schedule'] as $section_key => $section_value ?>
                        <?php if ($days) : ?></div><?php endif; ?>
                    <?php endforeach; // $schedule as $day_key => $day_value ?>
                </div>
            </div>
        </div>
    </div>
</div>

event/views/site/feedback.php
<?php
$this->title = 'Анкета - ' . $title;
use common\widgets\Alert;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                    <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                    <?php if ($questions) : ?>
                    <h1 class="event-title">Анкета</h1>
                    <?php
                        $active_form = ActiveForm::begin([
                            'enableClientValidation' => false,
                            'options' => ['autocomplete' => 'off'],
                        ]);

                        for ($i = 0; $i < count($questions); $i++) :
                            $field_label = $questions[$i]['question'];
                            $field_id = $questions[$i]['id'];
                    ?>
                    <div class="row">
                        <div class="col-12 col-lg-8">
                            <div class="input-group">
                            <?php
                                switch ($questions[$i]['type']) {
                                    // Input
                                    case 'I':
                                        echo $active_form
                                            ->field($form, 'answer[' . $field_id . ']')
                                            ->input('text')
                                            ->label($field_label);
                                        break;
                                    // Textarea
                                    case 'T':
                                    case 'TEXT':
                                        echo $active_form
                                            ->field($form, 'answer[' . $field_id . ']')
                                            ->textarea(['rows' => 5])
                                            ->label($field_label);
                                        break;
                                    // Checkbox
                                    case 'C':
                                        echo $active_form
                                            ->field($form, 'answer[' . $field_id . ']')
                                            ->checkboxList($questions[$i]['choice'], [
                                                'item' => function ($index, $label, $name, $checked, $value) use ($i) {
                                                    return '<input type="checkbox" id="checkbox-' . $i . $index . '" name="' . $name . '" value="' . $label . '" class="checkbox">
                                                            <label for="checkbox-' . $i . $index . '">' . $label . '</label>';
                                                }
                                            ])
                                            ->label($field_label);
                                        break;
                                    // Radio button
                                    case 'R':
                                        echo $active_form
                                            ->field($form, 'answer[' . $field_id . ']')
                                            ->radioList($questions[$i]['choice'], [
                                                'item' => function ($index, $label, $name, $checked, $value) use ($i) {
                                                    return '<input type="radio" id="radio-' . $i . $index . '" name="' . $name . '" value="' . $label . '" class="radio">
                                                            <label for="radio-' . $i . $index . '">' . $label . '</label>';
                                                }
                                            ])
                                            ->label($field_label);
                                        break;
                                }
                            ?>
                            </div>
                        </div>
                    </div>
                    <?php endfor; ?>
                    <div class="row">
                        <div class="col-12 col-lg-8 text-right">
                            <?=Html::submitButton('Отправить', ['class' => 'btn btn-primary']); ?>
                        </div>
                    </div>
                    <?php
                        ActiveForm::end();
                        else :
                    ?>
                    <div class="text-center">
                        <i class="fas fa-check-circle fa-7x text-success m-t-10"></i>
                        <div class="h3 m-t-10 m-b-5">В данный момент для вас нет активных анкет</div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

event/views/site/history.php
<?php
$this->title = 'История конференций';
use yii\widgets\ActiveForm;
use common\widgets\Alert;
use common\widgets\Sort;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                <h1>Посещенные конференции</h1>
                <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                <?php foreach ($events as $event) : ?>
                    <div class="item mb-3">
                        <a href="<?=Url::to(['handler/event', 'method' => 'event', 'id' => $event['id']]) ?>" class="h2"><?=$event['title']; ?></a>
                        <div class="mt-1 mb-2 text-lighten"><div class="far fa-calendar-alt text-primary"></div> <?=$event['date']; ?></div>
                    </div>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

event/views/site/index.php
<?php
$this->title = $event['title'];
use common\widgets\Alert;
use yii\helpers\Url;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                    <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                    <h1 class="event-title"><?=$event['title']; ?></h1>
                    <div class="row text-lighten">
                        <?php if ($event['location']) : ?>
                        <div class="col-12 col-md-auto">
                            <i class="fas fa-map-marker-alt text-primary m-r-5"></i> <span><?=$event['location']; ?></span>
                        </div>
                        <?php endif; ?>
                        <div class="col-12 col-md-auto">
                            <i class="far fa-calendar-alt text-primary m-r-5"></i> <?=$event['date']; ?>
                        </div>
                    </div>
                    <div class="m-t-10"><?=$event['desc']; ?></div>
                    <?php if ($schedule) : ?>
                    <h2 class="event-title mt-4">Программа конференции</h2>
                    <?php if (count($days) > 1) : ?>
                        <ul class="tab-nav my-2">
                        <?php foreach ($days as $day) : ?>
                            <li class="tab-nav-item<?=$day['active'] ? ' active' : ''; ?>" data-tab="<?=$day['id']; ?>"><?=$day['title'];?></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php foreach ($schedule as $day_key => $day_value) : // Цикл по дням ?>
                        <div <?=$days[$day_key]['active'] ? '' : ' class="d-none" '; ?>data-tab-content="<?=$days[$day_key]['id']; ?>">
                            <?php if (count($day_value['sections']) > 1) : ?>
                                <div class="row no-gutters">
                                    <div class="col-auto">
                                        <h3>Секции:</h3>
                                    </div>
                                    <div class="col">
                                    <?php foreach ($day_value['sections'] as $day_section) : // Цикл по секциям в дне ?>
                                        <a href="#section-<?=$day_section['id']; ?>" class="btn btn-link m-l-10"><?=$day_section['title']; ?></a>
                                    <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; // count($day_value['sections']) > 1 ?>
                            <?php foreach ($day_value['schedule'] as $section_key => $section_value) : ?>
                                <h3 id="section-<?=$day_value['sections'][$section_key]['id']; ?>" class="mt-3"><i class="fas fa-bullhorn text-primary"></i> <?=$day_value['sections'][$section_key]['title']; ?></h3>
                                <?php foreach ($section_value as $value) : ?>
                                    <?=$this->render('@event/views/_item/schedule-' . $value['type'], ['result' => $value, 'tab' => $day_key]); ?>
                                <?php endforeach; ?>
                            <?php endforeach; // $day_value['schedule'] as $section_key => $section_value ?>
                        </div>
                        <?php endforeach; // $schedule as $day_key => $day_value ?>
                    <?php endif; // $schedule ?>
                    <?=$this->render('@common/views/_partial/rating-form', ['form' => $form_rating, 'title' => 'Оцените доклад']); ?>
                </div>
            </div>
        </div>
    </div>
</div>

event/views/site/note.php
<?php
$this->title = 'Вопросы';
use yii\widgets\ActiveForm;
use common\widgets\Alert;
use common\widgets\Sort;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                    <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                    <h1 class="event-title">Заметки</h1>
                    <h3 class="m-b-15"><?=$schedule['title']; ?></h3>
                    <?php
                        $active_form = ActiveForm::begin([
                            'enableClientValidation' => false,
                            'options' => ['autocomplete' => 'off', 'enctype' => 'multipart/form-data'],
                        ]);
                    ?>
                    <div class="row">
                        <div class="col">
                            <div class="input-group">
                                <?=$active_form
                                    ->field($form, 'note')
                                    ->textarea(['rows' => 10, 'value' => $note])
                                    ->label(false);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row m-b-20">
                        <div class="col text-right">
                        <?=Html::submitButton('Сохранить', ['class' => 'btn btn-primary']); ?>
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

event/views/site/questions.php
<?php
$this->title = 'Вопросы';
use yii\widgets\ActiveForm;
use common\widgets\Alert;
use common\widgets\Sort;
use common\widgets\Answer;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<div class="main">
    <div class="container">
        <div class="d-block d-lg-none">
            <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <?=$this->render('@event/views/_partial/sidebar', ['nav' => 'event']); ?>
            </div>
            <div class="col-12 col-lg-10">
                <div class="block">
                    <?php if ($alert) echo Alert::Widget(['type' => $alert['type'], 'message' => $alert['message'], 'close' => $alert['close']]); ?>
                    <h1 class="event-title">Вопросы</h1>
                    <h3 class="m-b-15"><?=$schedule['title']; ?></h3>
                    <?php
                        if ($show_form) :
                            $active_form = ActiveForm::begin([
                                'enableClientValidation' => false,
                                'options' => ['autocomplete' => 'off'],
                            ]);
                    ?>
                    <div class="row">
                        <div class="col">
                            <div class="input-group">
                                <?=$active_form
                                    ->field($form, 'question')
                                    ->textarea(['rows' => 6])
                                    ->label('Ваш вопрос');
                                ?>
                                <?=$active_form
                                    ->field($form, 'id')
                                    ->input('hidden', ['value' => $id])
                                    ->label(false);
                                ?>
                                <?=$active_form
                                    ->field($form, 'schedule')
                                    ->input('hidden', ['value' => $schedule_id])
                                    ->label(false);
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="row m-b-20">
                        <div class="col text-right">
                        <?=Html::submitButton('Задать вопрос', ['class' => 'btn btn-primary']); ?>
                        </div>
                    </div>
                    <?php
                            ActiveForm::end();
                        endif;
                    ?>
                    <?php if ($questions) : ?>
                    <div class="row">
                        <div class="col">
                            <h2 id="questions" class="m-b-0">Список вопросов</h2>
                        </div>
                        <div class="col-auto p-t-5">
                            <strong>Сортировать:</strong>
                            <?=Sort::Widget([
                                'style' => 'sort m-b-10',
                                'items' => [
                                    [
                                        'sort' => '',
                                        'title' => 'По времени',
                                    ],
                                    [
                                        'sort' => 'like',
                                        'title' => 'По лайкам',
                                    ]
                                ]
                            ]); ?>
                        </div>
                    </div>
                    <?php for ($i = 0; $i < count($questions); $i++) : ?>
                        <div class="item m-b-10">
                            <div class="row m-b-5">
                                <div class="col">
                                    <i class="fas fa-user text-primary"></i> <?=$questions[$i]['author']; ?>
                                </div>
                                <div class="col-auto text-primary">
                                    <span id="likes"><?=$questions[$i]['like_count']; ?></span>
                                    <span id="liked" <?php if (!$questions[$i]['like']) : ?>class="d-none"<?php endif; ?>><i class="fas fa-thumbs-up fa-lg"></i></span>
                                    <span data-balloon="Мне нравится" <?php if ($questions[$i]['like']) : ?>class="d-none"<?php endif; ?> data-like data-schedule="<?=$schedule_id; ?>" data-question="<?=$questions[$i]['id']; ?>"><i class="far fa-thumbs-up fa-lg"></i></span>
                                </div>
                            </div>
                            <p><?=$questions[$i]['question']; ?></p>
                            <?php if ($questions[$i]['answer']) : ?>
                            <strong>Ответ спикера:</strong>
                            <p><?=$questions[$i]['answer']; ?></p>
                            <?php endif; ?>
                            <?php if (!$questions[$i]['answer'] && $questions[$i]['can_answer']) : ?>
                            <button data-answer data-fancybox data-src="#answer-modal" data-question="<?=$questions[$i]['question']; ?>" data-id="<?=$questions[$i]['id']; ?>" class="btn btn-link m-b-5">Ответить</button>
                            <?=$this->render('@event/views/_partial/answer-form', ['id' => 'answer-modal', 'form' => $form_answer]); ?>
                            <?php endif; ?>
                        </div>
                    <?php
                            endfor;
                        else:
                    ?>
                        <p>Нет вопросов</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="btn-fixed" data-page-update><i class="fas fa-redo-alt"></i></div>
</div>